import { Game } from "./configuration";

const defaultGames: Game[] = [
  {
    "name": "mycity",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "cty_board_{{player_id}}",
    "playerPanelOffset": -10,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff"
  },
  {
    "name": "abyss",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-panel-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": ".desktop_version #centered-table { margin-left: 46px; }"
  },
  {
    "name": "conspiracy",
    "position": "bottom",
    "positionBottom": "140px",
    "left": "12px",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": ".show-playermat-button { visibility: hidden; }"
  },
  {
    "name": "thurnandtaxis",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "miniboard_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#thurntaxis_board, .desktop_version #page-title { margin-left: 55px; }"
  },
  {
    "name": "seasons",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "anchor_player_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version .tableau { margin-left: 46px; } .anchor-up { display: none; } .show-player-tableau { visibility: hidden; }"
  },
  {
    "name": "azul",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-hand-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000"
  },
  {
    "name": "wingspan",
    "position": "auto",
    "positionTop": "150px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "aviary_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #wsp_opponent_board_area { padding-left: 40px; }"
  },
  {
    "name": "architectsofthewestkingdom",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-title { margin-left: 52px; } .desktop_version #pagesection_gameview { padding-left: 52px; }"
  },
  {
    "name": "amerigo",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "playersection_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#playersections { padding-left: 50px; }"
  },
  {
    "name": "agricola",
    "position": "auto",
    "positionTop": "150px",
    "positionBottom": "auto",
    "left": "6px",
    "playerPanel": "player-board-resizable-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #position-wrapper { padding-left: 52px; }"
  },
  {
    "name": "akropolis",
    "position": "top",
    "positionTop": "40vh",
    "left": "0.5em",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#jump-controls { display: none; }"
  },
  {
    "name": "villagers",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "vil_village_{{player_id}}",
    "playerPanelOffset": 0,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #villages { margin-left: 50px; }"
  },
  {
    "name": "spots",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "spt-cards{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #spt-gameArea { margin-left: 25px; }"
  },
  {
    "name": "astra",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "tbp-playerCards-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #tbp { margin-left: 50px; }"
  },
  {
    "name": "earth",
    "position": "top",
    "positionTop": "40vh",
    "left": "0.5em",
    "boardPanel": "ea-area-common",
    "boardPanelOffset": 5,
    "playerPanel": "ea-area-player-{{player_id}}",
    "playerPanelOffset": 0,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": "#ea-shortcut-area { visibility: hidden; }"
  },
  {
    "name": "gizmos",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "gizmo_track_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #gizmos_board { margin-left: 50px; }"
  },
  {
    "name": "potionexplosion",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "playerArea_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #game_play_area { margin-left: 50px; }"
  },
  {
    "name": "spacebase",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "playerTable_{{player_id}}",
    "playerPanelOffset": 45,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": ".desktop_version #game_play_area { margin-left: 50px; }"
  },
  {
    "name": "raceforthegalaxy",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "tableau_panel_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#a3adb7",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": ".desktop_version #game_play_area { padding-left: 50px; }"
  },
  {
    "name": "greatwesterntrail",
    "position": "auto",
    "positionTop": "150px",
    "positionBottom": "auto",
    "left": "6px",
    "playerPanel": "player_area_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #game_play_area_wrap { padding-left: 50px; }"
  },
  {
    "name": "throughtheagesnewstory",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player_tableau_wrap_{{player_id}}",
    "playerPanelOffset": 45,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #game_play_area { padding-left: 50px; }"
  },
  {
    "name": "throughtheages",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player_tableau_{{player_id}}",
    "playerPanelOffset": 45,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #game_play_area { padding-left: 50px; }"
  },
  {
    "name": "getonboard",
    "position": "top",
    "positionTop": "40vh",
    "left": "0.5em",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#jump-controls { display: none; }"
  },
  {
    "name": "lumen",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-content { padding-left: 50px; }"
  },
  {
    "name": "gardennation",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-content { padding-left: 50px; }"
  },
  {
    "name": "tapestry",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "playerArea_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-content { padding-left: 50px; } #player_board_config { background-color: rgb(218, 211, 193); }"
  },
  {
    "name": "resarcana",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player_area_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-content { padding-left: 50px; }"
  },
  {
    "name": "innovation",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version .player { margin-left: 50px; }"
  },
  {
    "name": "railroadink",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-area-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #all-players { padding-left: 50px; }"
  },
  {
    "name": "viticulture",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "playerboard_row_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #vit_game { padding-left: 50px; }"
  },
  {
    "name": "hadara",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "game_board_{{player_id}}",
    "playerPanelOffset": 10,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "customZoomContainer": "pagesection_gameview",
    "css": ".desktop_version #page-content { padding-left: 50px; }"
  },
  {
    "name": "gogoa",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "goa-holder-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#page-title { width: 100% !important } .desktop_version #page-content { padding-left: 50px; }"
  }
];

export default defaultGames;