const filteredLogs = [
  'is now online',
  'est maintenant connecté·e',
  'عبر الإنترنت',
  'у анлайне',
  'е сега онлайн',
  'a zo kennasket',
  'està en línia',
  'je online',
  'er nu online',
  'ist jetzt online',
  'συνδέθηκε',
  'se ha conectado',
  'logis sisse',
  'آنلاین شده است',
  'on nyt online',
  'está agora en liña',
  'מחובר/ת כעת',
  'abhi online hein',
  'bejelentkezett',
  'sekarang online',
  'è ora online',
  'がオンラインになりました',
  'prisijungė',
  'tagad ir tiešsaistē',
  'telah online',
  'er nå pålogget',
  'is nu online',
  'jest online',
  'está agora online',
  'tocmai s-a conectat',
  'в сети',
  'je teraz pripojený',
  'kom online',
  'ออนไลน์',
  'çevrimiçi oldu',
  'зараз онлайн',
  'đã online',
  '已上线',
  '現已上線',
  'is now offline',
  's\'est déconnecté·e',
  'غير متصل',
  'у афлайне',
  'е сега офлайн',
  'a zo digennasket',
  'ara està fora de línia',
  'je offline',
  'er nu offline',
  'ist jetzt offline',
  'αποσυνδέθηκε',
  'se ha desconectado',
  'on nüüd väljas',
  'آفلاین شده است',
  'on nyt offline',
  'está agora desconectado',
  'לא מחובר/ת',
  'abhi offline hein',
  'kijelentkezett',
  'sekarang offline',
  'si è disconnesso',
  'がオフラインになりました',
  '님이 오프라인 상태가 되었습니다',
  'atsijungė',
  'tagad ir bezsaitē',
  'telah offline',
  'er nå avlogget',
  'is nu offline',
  'jest offline',
  'está agora offline',
  'tocmai s-a deconectat',
  'не в сети',
  'sa odhlásil',
  'gick offline',
  'ออฟไลน์',
  'çevrimdışı oldu',
  'зараз офлайн',
  'đã thoát',
  '已离线',
  '現已離線'
];

const shouldFilter = (text: string) => {
  return filteredLogs.some(t => text.indexOf(t) >= 0);
};

export default shouldFilter;